#ifndef SUSFS_DEFS_H
#define SUSFS_DEFS_H

/*************************
 ** Define Const Values **
 *************************/
#define TAG "ksu_susfs"
#define KSU_INSTALL_MAGIC1 0xDEADBEEF
#define SUSFS_MAGIC 0xFAFAFAFA

/* Stable SUSFS v2.x command namespace. */
#define CMD_SUSFS_ADD_SUS_PATH 0x55550
#define CMD_SUSFS_ADD_SUS_PATH_LOOP 0x55553
#define CMD_SUSFS_HIDE_SUS_MNTS_FOR_NON_SU_PROCS 0x55561
#define CMD_SUSFS_ADD_SUS_KSTAT 0x55570
#define CMD_SUSFS_UPDATE_SUS_KSTAT 0x55571
#define CMD_SUSFS_ADD_SUS_KSTAT_STATICALLY 0x55572
#define CMD_SUSFS_SET_UNAME 0x55590
#define CMD_SUSFS_ENABLE_LOG 0x555a0
#define CMD_SUSFS_SET_CMDLINE_OR_BOOTCONFIG 0x555b0
#define CMD_SUSFS_ADD_OPEN_REDIRECT 0x555c0
#define CMD_SUSFS_SHOW_VERSION 0x555e1
#define CMD_SUSFS_SHOW_ENABLED_FEATURES 0x555e2
#define CMD_SUSFS_SHOW_VARIANT 0x555e3
#define CMD_SUSFS_QUERY_CAPABILITIES 0x555e5
#define CMD_SUSFS_ENABLE_AVC_LOG_SPOOFING 0x60010
#define CMD_SUSFS_ADD_SUS_MAP 0x60020

#define SUSFS_CAPS_ABI_VERSION 1
#define SUSFS_CAP_SUS_PATH (1ULL << 0)
#define SUSFS_CAP_SUS_MOUNT (1ULL << 1)
#define SUSFS_CAP_SUS_KSTAT (1ULL << 2)
#define SUSFS_CAP_SPOOF_UNAME (1ULL << 3)
#define SUSFS_CAP_ENABLE_LOG (1ULL << 4)
#define SUSFS_CAP_HIDE_SYMBOLS (1ULL << 5)
#define SUSFS_CAP_SPOOF_CMDLINE_OR_BOOTCONFIG (1ULL << 6)
#define SUSFS_CAP_OPEN_REDIRECT (1ULL << 7)
#define SUSFS_CAP_SUS_MAP (1ULL << 8)
#define SUSFS_CAP_AVC_LOG_SPOOFING (1ULL << 9)

#define SUSFS_MAX_LEN_PATHNAME 256
#define SUSFS_ENABLED_FEATURES_SIZE 8192
#define SUSFS_MAX_VERSION_BUFSIZE 16
#define SUSFS_MAX_VARIANT_BUFSIZE 16

/******************
 ** Define Macro **
 ******************/
#define ERR_CMD_NOT_SUPPORTED 126
#define log(fmt, msg...) printf(fmt, ##msg);
#define PRT_MSG_IF_CMD_NOT_SUPPORTED(x, cmd) if (x == ERR_CMD_NOT_SUPPORTED) log("[-] CMD: '0x%x', SUSFS operation not supported, please enable it in kernel\n", cmd)

#endif // #ifndef SUSFS_DEFS_H
